---

- file:
    path: "{{ item }}"
    state: directory
    owner: p2p
    group: p2p
  with_items:
    - "{{ rtorrent_downloads }}"
    - "{{ sonarr_downloads }}"
    - "{{ radarr_downloads }}"
    - "{{ plex_movies }}"
    - "{{ plex_tv }}"
    - "{{ bazarr_config }}"

- name: Containers internal network
  docker_network:
    name: p2p

- name: Launch Rtorrent
  docker_container:
    name: rtorrent
    image: diameter/rtorrent-rutorrent:stable
    state: started
    env:
        USR_ID: "{{ p2p_uid }}"
        GRP_ID: "{{ group_gid }}"
        NOIPV6: 1
    ports:
      - "49160:49160"
      - "49161:49161"
    volumes:
      - "{{ rtorrent_downloads }}:/downloads"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - name: p2p

- name: Plex
  docker_container:
    name: plex
    image: plexinc/pms-docker:latest
    state: started
    env:
        PLEX_UID: "{{ plex_uid }}"
        PLEX_GID: "{{ group_gid }}"
        PLEX_CLAIM: "{{ plex_claim_token }}"
        ADVERTISE_IP: "{{ ansible_host }}"
    volumes:
      - "{{ plex_movies }}:/data/movies"
      - "{{ plex_tv }}:/data/tv"
      - "{{ plex_transcode }}:/transcode"
      - "{{ plex_config }}:/config"
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - "32400:32400"
    networks:
      - name: p2p


- name: Radarr
  docker_container:
    name: radarr
    image: linuxserver/radarr:latest
    state: started
    volumes:
      - "/etc/radarr:/config"
      - "{{ radarr_downloads }}:/downloads/movies"
      - "{{ plex_movies }}:/movies"
      - "/etc/localtime:/etc/localtime:ro"
    env:
        PUID: "{{ p2p_uid }}"
        PGID: "{{ group_gid }}"
    networks:
      - name: p2p
        links:
          - rtorrent:rtorrent

- name: Sonarr
  docker_container:
    name: sonarr
    image: linuxserver/sonarr:latest
    state: started
    volumes:
      - "/etc/sonarr:/config"
      - "{{ sonarr_downloads }}:/downloads/tv"
      - "{{ plex_tv }}:/tv"
      - "/etc/localtime:/etc/localtime:ro"
    env:
        PUID: "{{ p2p_uid }}"
        PGID: "{{ group_gid }}"
    networks:
      - name: p2p
        links:
          - rtorrent:rtorrent

- name: Bazarr
  docker_container:
    name: bazarr
    image: morpheus65535/bazarr:latest
    state: started
    env:
        PUID: "{{ p2p_uid }}"
        PGID: "{{ group_gid }}"
    volumes:
      - "{{ plex_movies }}:/movies"
      - "{{ plex_tv }}:/tv"
      - "{{ bazarr_config }}:/bazarr/data"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - name: p2p
        links:
          - sonarr:sonarr
          - radarr:radarr

- name: Jackett
  docker_container:
    name: jackett
    image: linuxserver/jackett:latest
    state: started
    volumes:
      - "/etc/jackett:/config/Jackett"
      - "{{ torrent_blackhole }}:/downloads"
      - "/etc/localtime:/etc/localtime:ro"
    env:
        PUID: "{{ p2p_uid }}"
        PGID: "{{ group_gid }}"
    ports:
      - "8080:9117"
    # networks:
    #   - name: p2p

- name: Tautulli
  docker_container:
    name: tautulli
    image: tautulli/tautulli:latest
    state: started
    volumes:
      - "/etc/tautulli:/config"
      - "{{ plex_config }}/Library/Application Support/Plex Media Server/Logs:/plex_logs:ro"
      - "/etc/localtime:/etc/localtime:ro"
    env:
        PUID: "{{ p2p_uid }}"
        PGID: "{{ group_gid }}"
    networks:
      - name: p2p

- name: Ombi
  docker_container:
    name: ombi
    image: linuxserver/ombi:latest
    state: started
    volumes:
      - "/etc/ombi:/config"
      - "/etc/localtime:/etc/localtime:ro"
    env:
        PUID: "{{ p2p_uid }}"
        PGID: "{{ group_gid }}"
    networks:
      - name: p2p
        links:
          - plex:plex
          - sonarr:sonarr
          - radarr:radarr

- name: Netdata
  docker_container:
    name: netdata
    image: firehol/netdata:latest
    capabilities: "SYS_PTRACE"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - name: p2p

- name: Caddyfile
  template:
    src: caddyfile.j2
    dest: /etc/Caddyfile

- name: Reverse-Proxy
  docker_container:
    name: reverse-proxy
    image: abiosoft/caddy
    state: started
    # restart: yes
    volumes:
      - "/etc/Caddyfile:/etc/Caddyfile"
      # - "/var/caddy/srv:/var/www/html"
      - "/etc/caddy/certs:/root/.caddy"
      - "/etc/localtime:/etc/localtime:ro"
    env:
        ACME_AGREE: true
    ports:
      - "80:80"
      - "443:443"
    networks:
      - name: p2p
        links:
          - rtorrent:rtorrent
          - radarr:radarr
          - sonarr:sonarr
          - plex:plex
          - bazarr:bazarr
          - tautulli:tautulli
          - ombi:ombi
          - netdata:netdata