---
rtorrent_config: "/etc/rtorrent"
plex_config: "/var/plex"
bazarr_config: "/etc/bazarr"

medias_root: "/var/lib/medias"
rtorrent_downloads: "{{ medias_root }}/downloads"
sonarr_downloads: "{{ rtorrent_downloads }}/tv"
radarr_downloads: "{{ rtorrent_downloads }}/movies"
torrent_blackhole: "{{ rtorrent_downloads }}/blackhole"

exposed_folder: "{{ rtorrent_downloads }}/others"

plex_medias: "{{ medias_root }}/plex"
plex_movies: "{{ plex_medias }}/movies"
plex_tv: "{{ plex_medias }}/tv"
plex_transcode: "{{ plex_medias }}/transcode"
