---
- name: Directories permissions
  file:
    path: "{{ item }}"
    state: directory
    owner: p2p
    group: p2p
  with_items:
    - "{{ rtorrent_downloads }}"
    - "{{ sonarr_downloads }}"
    - "{{ radarr_downloads }}"
    - "{{ plex_movies }}"
    - "{{ plex_tv }}"
    - "{{ bazarr_config }}"
    - "{{ exposed_folder }}"

- name: Setting containers
  include_tasks: "{{ item }}.yml"
  with_items:
    - traefik
    - portainer
    - plex
    - rtorrent
    - jackett
    - sonarr
    - radarr
    - ombi
    - tautulli
    - bazarr
    - lighttpd
    - thelounge
    - h5ai
    - watchtower
