---
- name: Ensuring group 'wheel' exists
  group:
    name: "wheel"
    state: present

- name: "Ensuring group '{{ group_name }}' exists"
  group:
    name: "{{ group_name }}"
    state: present
    gid: "{{ group_gid }}"

- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: Creating users
  user: 
    name: "{{ item.name }}"
    groups: "{{ item.groups}} "
    append: "{{ item.append}}"
    state: present
    createhome: "{{ item.createhome }}"
    uid: "{{ item.uid }}"
    shell: "{{ item.shell }}"
  with_items:
    - { name: "deployer", groups: "wheel", append: yes, createhome: yes , uid: "1000", shell: "/bin/bash" }
    - { name: "{{ p2p_user }}", groups: "{{ group_name }}", append: yes, createhome: no, uid: "{{ p2p_uid }}", shell: "/bin/bash" }
    - { name: "{{ plex_user }}", groups: "{{ group_name }}", append: yes, createhome: no, uid: "{{ plex_uid }}", shell: "/sbin/nologin" }
    # - { name: "{{ netdata_user }}", groups: "docker", append: yes, createhome: no, uid: "{{ netdata_uid }}", shell: "/sbin/nologin" }

- name: Set up authorized keys for the deployer user
  authorized_key: 
    user: deployer 
    key: "{{ item }}"
  with_file:
    - "~/.ssh/id_rsa.pub"

- name: Upgrade all packages except kernel
  yum:
    name: '*'
    state: latest
    exclude: kernel*
