---

# services roots for reverse proxy use
# UNUSED FOR NOW
rtorrent_root: "/"
radarr_root: "/"
sonarr_root: "/"
jackett_root: "/"
plex_root: "/"
ombi_root: "/"


rtorrent_config: "/etc/rtorrent"
plex_config: "/var/plex"

p2p_root: "/var/lib/downloads"
rtorrent_downloads: "{{ p2p_root }}"
sonarr_downloads: "{{ rtorrent_downloads }}/tv"
radarr_downloads: "{{ rtorrent_downloads }}/movies"
torrent_blackhole: "{{ p2p_root }}/blackhole"


plex_medias: "/var/lib/plex"
plex_movies: "{{ plex_medias }}/movies"
plex_tv: "{{ plex_medias }}/tv"
plex_transcode: "{{ plex_medias }}/transcode"

